# Generated by Django 5.2.17 on 2026-09-04 22:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('reassign_customer', 'Reassign Customer'), ('reassign_committee', 'Reassign Committee'), ('reassign_technical', 'Reassign Technical'), ('reassign_both_committees', 'Reassign Both Committees')], max_length=60)),
                ('name_en', models.CharField(max_length=20, unique=True)),
                ('name_ar', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=20, unique=True)),
                ('name_ar', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=20, unique=True)),
                ('name_ar', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=20, unique=True)),
                ('name_ar', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name_en', models.CharField(max_length=20, unique=True)),
                ('name_ar', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('beneficiary', 'Beneficiary'), ('direct', 'Direct'), ('distributor', 'Distributor'), ('multi_branch', 'Multi Branch'), ('admin', 'Admin'), ('branch_manager', 'Branch Manager'), ('sales_manager', 'Sales Manager'), ('ceo', 'CEO'), ('committee_member', 'Committee Member'), ('technical_member', 'Technical Member'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.customercategory')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.product')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.customer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.requeststatus')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.requesttype')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeForm',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.request')),
            ],
        ),
        migrations.CreateModel(
            name='RequestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asked_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.request')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovelWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('initial_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.requeststatus')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='requests.requesttype')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalForm',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.request')),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_final', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.action')),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_status', to='requests.requeststatus')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_status', to='requests.requeststatus')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='requests.approvelworkflow')),
            ],
        ),
        migrations.AddConstraint(
            model_name='approvelworkflow',
            constraint=models.UniqueConstraint(fields=('request_type', 'initial_status'), name='unique_request_type_initial_status'),
        ),
    ]
