# Generated by Django 5.2.17 on 2026-09-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_requeststatus_name_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('assign_committee', 'Assign Committee'), ('assign_technical', 'Assign Technical'), ('approve', 'Approve'), ('reject', 'Reject'), ('reassign_customer', 'Reassign Customer'), ('reassign_committee', 'Reassign Committee'), ('reassign_technical', 'Reassign Technical'), ('reassign_both_committees', 'Reassign Both Committees')], max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ar',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
