# Generated by Django 5.2.17 on 2026-09-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_action_type_alter_product_name_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='name_ar',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='name_en',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
