# Generated by Django 5.2.17 on 2026-09-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_action_name_ar_alter_action_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('assign_committee', 'Assign Committee'), ('assign_technical', 'Assign Technical'), ('approve', 'Approve'), ('reject', 'Reject'), ('reassign_customer', 'Reassign Customer'), ('reassign_committee', 'Reassign Committee'), ('reassign_technical', 'Reassign Technical'), ('reassign_both_committees', 'Reassign Both Committees'), ('save_form', 'Save Form')], max_length=60),
        ),
        migrations.AddConstraint(
            model_name='transition',
            constraint=models.UniqueConstraint(fields=('workflow', 'from_status', 'to_status', 'action'), name='unique_workflow_from_status_to_status'),
        ),
    ]
