# Generated by Django 5.2.17 on 2026-09-05 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_alter_action_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSequence',
            fields=[
                ('sequence', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('assign_committee', 'Assign Committee'), ('assign_technical', 'Assign Technical'), ('approve', 'Approve'), ('reject', 'Reject'), ('reassign_customer', 'Reassign Customer'), ('reassign_committee', 'Reassign Committee'), ('reassign_technical', 'Reassign Technical'), ('reassign_both_committees', 'Reassign Both Committees'), ('save_form', 'Save Form'), ('gfsa_action', 'GFSA Action')], max_length=60),
        ),
        migrations.AlterField(
            model_name='request',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requests.customer'),
        ),
    ]
