# Generated by Django 5.2.17 on 2026-09-05 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_requestsequence_alter_action_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestSequence',
        ),
    ]
