# Generated by Django 5.2.17 on 2026-09-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_delete_requestsequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
