# Generated by Django 5.2.17 on 2026-09-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_requestsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='can_reopen',
            field=models.BooleanField(default=False, help_text='If is_final is True, This field helps to determine if the request can be reopened after that or not'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='is_final',
            field=models.BooleanField(default=False, help_text='Helps to determine if the transition can be the final stage of the workflow for the request type or not'),
        ),
    ]
