# Generated by Django 5.2.17 on 2026-09-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_transition_can_reopen_alter_transition_is_final'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transition',
            name='unique_workflow_from_status_to_status',
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('assign_committee', 'Assign Committee'), ('assign_technical', 'Assign Technical'), ('approve', 'Approve'), ('reject', 'Reject'), ('reopen', 'Reopen'), ('reassign_customer', 'Reassign Customer'), ('reassign_committee', 'Reassign Committee'), ('reassign_technical', 'Reassign Technical'), ('reassign_both_committees', 'Reassign Both Committees'), ('save_technical_form', 'Save Technical Form'), ('save_committee_form', 'Save Committee Form'), ('gfsa_action', 'GFSA Action')], max_length=60),
        ),
        migrations.AlterField(
            model_name='transition',
            name='is_final',
            field=models.BooleanField(default=False, help_text='Helps to determine if the transition can be final stage of the workflow for the request type or not'),
        ),
        migrations.AddConstraint(
            model_name='transition',
            constraint=models.UniqueConstraint(fields=('workflow', 'from_status', 'to_status', 'action'), name='unique_workflow_from_status_to_status_action'),
        ),
    ]
