# Generated by Django 5.2.17 on 2026-09-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_remove_transition_unique_workflow_from_status_to_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transition',
            name='can_reopen',
        ),
    ]
