# Generated by Django 6.1.1 on 2026-09-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0011_remove_transition_can_reopen"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="approvelworkflow",
            name="unique_request_type_initial_status",
        ),
        migrations.RemoveConstraint(
            model_name="transition",
            name="unique_workflow_from_status_to_status_action",
        ),
        migrations.RemoveField(
            model_name="approvelworkflow",
            name="initial_status",
        ),
        migrations.RemoveField(
            model_name="approvelworkflow",
            name="request_type",
        ),
        migrations.RemoveField(
            model_name="transition",
            name="action",
        ),
        migrations.RemoveField(
            model_name="transition",
            name="from_status",
        ),
        migrations.RemoveField(
            model_name="transition",
            name="to_status",
        ),
        migrations.RemoveField(
            model_name="transition",
            name="workflow",
        ),
        migrations.DeleteModel(
            name="Action",
        ),
        migrations.DeleteModel(
            name="ApprovelWorkflow",
        ),
        migrations.DeleteModel(
            name="Transition",
        ),
    ]
