# Generated by Django 6.1.1 on 2026-09-07 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "requests",
            "0012_remove_approvelworkflow_unique_request_type_initial_status_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("assign_committee", "Assign Committee"),
                            ("assign_technical", "Assign Technical"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("reopen", "Reopen"),
                            ("reassign_customer", "Reassign Customer"),
                            ("reassign_committee", "Reassign Committee"),
                            ("reassign_technical", "Reassign Technical"),
                            ("reassign_both_committees", "Reassign Both Committees"),
                            ("save_technical_form", "Save Technical Form"),
                            ("save_committee_form", "Save Committee Form"),
                            ("gfsa_action", "GFSA Action"),
                        ],
                        max_length=60,
                    ),
                ),
                ("name_en", models.CharField(max_length=50, unique=True)),
                ("name_ar", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ApprovelWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "initial_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requests.requeststatus",
                    ),
                ),
                (
                    "request_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_workflows",
                        to="requests.requesttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        default=False,
                        help_text="Helps to determine if the transition can be final stage of the workflow for the request type or not",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflow.action",
                    ),
                ),
                (
                    "from_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_status",
                        to="requests.requeststatus",
                    ),
                ),
                (
                    "to_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_status",
                        to="requests.requeststatus",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="workflow.approvelworkflow",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="approvelworkflow",
            constraint=models.UniqueConstraint(
                fields=("request_type", "initial_status"),
                name="unique_request_type_initial_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="transition",
            constraint=models.UniqueConstraint(
                fields=("workflow", "from_status", "to_status", "action"),
                name="unique_workflow_from_status_to_status_action",
            ),
        ),
    ]
